name: Compile + Deploy to Preview

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit hooks
        run: pre-commit run --all-files

  build:
    needs: pre-commit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Set up cwebp
        run: sudo apt-get install -y webp

      - name: Convert Images to WebP and remove original files
        run: |
          shopt -s globstar nullglob  # Enable recursive glob and handle no-match as empty result
          for file in assets/img/**/*.{png,PNG,jpg,JPG,jpeg,JPEG}
          do
            cwebp "$file" -o "${file%.*}.webp"
            rm "$file"
          done

      - name: Update references from PNG, JPG to WebP
        run: |
          find ./ -type f -not -path "./.git/*" -exec grep -IlE '\.png|\.PNG|\.jpg|\.JPG|\.jpeg|\.JPEG' {} + | xargs sed -i -e 's/\.png/\.webp/g' -e 's/\.PNG/\.webp/g' -e 's/\.jpg/\.webp/g' -e 's/\.JPG/\.webp/g' -e 's/\.jpeg/\.webp/g' -e 's/\.JPEG/\.webp/g'

      - name: Remove .git directory
        run: rm -rf ./.git

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}

    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    steps:
      - uses: actions/download-artifact@master
        with:
          name: page
          path: .
      - uses: actions/configure-pages@v1
      - uses: actions/upload-pages-artifact@v1
        with:
          path: .
      - id: deployment
        uses: actions/deploy-pages@main
