name: test scss compile

on:
  workflow_dispatch:
  push:
    branches:
      - add-scss-compile

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update Submodules
        run: |
          git submodule update --init --recursive
          git submodule foreach git pull origin main

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install SCSS Compiler and Bootstrap
        run: |
          cd ops
          npm install

      - name: Compile SCSS
        run: |
          cd ops
          npm run sass

      - name: Replace GA_MEASUREMENT_ID in HTML files
        run: find ./ -type f -name "*.html" -exec sed -i 's/GA_MEASUREMENT_ID/${{ secrets.GA_MEASUREMENT_ID }}/g' {} \;